# Generated by Django 4.1.13 on 2026-02-28 11:33

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, default='', max_length=50, verbose_name='昵称')),
                ('avatar', models.CharField(blank=True, default='', max_length=500, verbose_name='头像URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'novel_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NovelChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(db_index=True, max_length=20, verbose_name='小说ID')),
                ('chapter_title', models.CharField(max_length=255, verbose_name='章节标题')),
                ('chapter_url', models.CharField(blank=True, default='', max_length=500, verbose_name='章节链接')),
                ('is_vip', models.SmallIntegerField(default=0, verbose_name='是否VIP（0免费，1VIP）')),
                ('chapter_order', models.IntegerField(default=0, verbose_name='章节顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'db_table': 'novel_chapters',
                'ordering': ['book_id', 'chapter_order'],
            },
        ),
        migrations.CreateModel(
            name='NovelDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='小说ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('author', models.CharField(blank=True, default='', max_length=100, verbose_name='作者')),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='分类')),
                ('sub_category', models.CharField(blank=True, default='', max_length=50, verbose_name='子分类')),
                ('tags', models.CharField(blank=True, default='', max_length=255, verbose_name='标签')),
                ('intro', models.TextField(blank=True, default='', verbose_name='简介')),
                ('month_read', models.IntegerField(default=0, verbose_name='月阅读数')),
                ('month_flower', models.IntegerField(default=0, verbose_name='月鲜花数')),
                ('total_read', models.IntegerField(default=0, verbose_name='总阅读数')),
                ('total_flower', models.IntegerField(default=0, verbose_name='总鲜花数')),
                ('score', models.DecimalField(db_index=True, decimal_places=1, default=0.0, max_digits=3, verbose_name='评分')),
                ('score_count', models.IntegerField(default=0, verbose_name='评分人数')),
                ('in_time', models.CharField(blank=True, default='', max_length=50, verbose_name='入站时间')),
                ('update_time', models.CharField(blank=True, default='', max_length=50, verbose_name='更新时间')),
                ('total_words', models.IntegerField(default=0, verbose_name='总字数')),
                ('read_url', models.CharField(blank=True, default='', max_length=500, verbose_name='阅读链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '小说详情',
                'verbose_name_plural': '小说详情',
                'db_table': 'novel_detail',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='NovelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='小说ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('author', models.CharField(blank=True, default='', max_length=100, verbose_name='作者')),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='分类')),
                ('week_click', models.IntegerField(db_index=True, default=0, verbose_name='周点击')),
                ('word_count', models.CharField(blank=True, default='', max_length=50, verbose_name='字数')),
                ('date_label', models.CharField(blank=True, default='', max_length=50, verbose_name='日期标签')),
                ('intro', models.TextField(blank=True, default='', verbose_name='简介')),
                ('latest_chapter', models.CharField(blank=True, default='', max_length=255, verbose_name='最新章节标题')),
                ('book_url', models.CharField(blank=True, default='', max_length=500, verbose_name='小说详情页链接')),
                ('latest_url', models.CharField(blank=True, default='', max_length=500, verbose_name='最新章节链接')),
                ('cover_url', models.CharField(blank=True, default='', max_length=500, verbose_name='封面图片URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '小说列表',
                'verbose_name_plural': '小说列表',
                'db_table': 'novel_list',
                'ordering': ['-week_click'],
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(db_index=True, max_length=20, verbose_name='小说ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
                'db_table': 'novel_user_favorite',
            },
        ),
        migrations.AddIndex(
            model_name='novelchapter',
            index=models.Index(fields=['book_id', 'chapter_order'], name='novel_chapt_book_id_499e4c_idx'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['user', 'book_id'], name='novel_user__user_id_07562a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together={('user', 'book_id')},
        ),
    ]
